AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: SAM app that sends a fax when an object is uploaded to S3.

Resources:
  SendFaxLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app/send_fax.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: Gets object, prints name.
      MemorySize: 256
      Timeout: 30
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 's3:GetObject'
              Resource: 'arn:aws:s3:::*'
            - Effect: Allow
              Action:
              - ssm:GetParameter
              Resource:
              - Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/prod/send_fax/account_sid
              - Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/prod/send_fax/auth_token
              - Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/prod/send_fax/to_number
              - Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/prod/send_fax/from_number
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket: 
              Ref: SendFaxBucket
            Events:
              - 's3:ObjectCreated:*'
  
  SendFaxBucket:
    Type: 'AWS::S3::Bucket'
